# Generated by Django 2.2.24 on 2022-12-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    def is_building_new(self, schema_editor):
        Flat = self.get_model('property', 'Flat')
        flats = Flat.objects.all()
        flats_iterator = flats.iterator()
        try:
            first_flat = next(flats_iterator)
        except StopIteration:
            pass
        else:
            from itertools import chain
            for flat in chain([first_flat], flats_iterator):
                flat.new_building = (flat.construction_year >= 2015)
                flat.save()

    dependencies = [
        ('property', '0004_auto_20221205_1640'),
    ]

    operations = [
        migrations.RunPython(is_building_new, migrations.RunPython.noop)
    ]
