# Generated by Django 2.2.24 on 2022-12-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    def is_building_new(self, schema_editor):
        Flat = self.get_model('property', 'Flat')
        Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
        Flat.objects.filter(construction_year__lt=2015).update(new_building=True)

    dependencies = [
        ('property', '0004_auto_20221205_1640'),
    ]

    operations = [
        migrations.RunPython(is_building_new, migrations.RunPython.noop)
    ]
