# Generated by Django 2.2.24 on 2022-12-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    def is_building_new(self, schema_editor):
        Flat = self.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            if flat.construction_year >= 2015:
                flat.new_building = True
                flat.save()
            else:
                flat.new_building = False
                flat.save()

    dependencies = [
        ('property', '0004_auto_20221205_1640'),
    ]

    operations = [
        migrations.RunPython(is_building_new, migrations.RunPython.noop)
    ]
