# Generated by Django 2.2.24 on 2022-12-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20221206_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет'), (None, 'Неизвестно')], default=None, null=True, verbose_name='Новостройка'),
        ),
    ]
