# Generated by Django 2.2.24 on 2022-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221207_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(related_name='liked_flats', to='property.Flat', verbose_name='Кто лайкнул'),
        ),
    ]
