# Generated by Django 2.2.24 on 2022-12-07 23:34
import phonenumbers
from django.db import migrations


class Migration(migrations.Migration):

    def parse_numbers(self, schema_editor):
        Flat = self.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            if flat.owners_phonenumber:
                unparsed_number = flat.owners_phonenumber
                parsed_number = phonenumbers.parse(unparsed_number, 'RU')
                if phonenumbers.is_possible_number(parsed_number) and phonenumbers.is_valid_number(parsed_number):
                    flat.owner_pure_phone = phonenumbers.format_number(parsed_number,
                                                                       phonenumbers.PhoneNumberFormat.E164
                                                                       )
                    flat.save()

    dependencies = [
        ('property', '0015_auto_20221208_0129'),
    ]

    operations = [
        migrations.RunPython(parse_numbers, migrations.RunPython.noop)
    ]
