# Generated by Django 2.2.24 on 2022-12-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    def load_users(self, schema_editor):
        Flat = self.get_model('property', 'Flat')
        Owner = self.get_model('property', 'Owner')
        flats = Flat.objects.all()
        flats_iterator = flats.iterator()
        try:
            first_flat = next(flats_iterator)
        except StopIteration:
            pass
        else:
            from itertools import chain
            for flat in chain([first_flat], flats_iterator):
                Owner.objects.get_or_create(name=flat.owner,
                                            phonenumber=flat.owners_phonenumber,
                                            owner_phonenumber=flat.owner_pure_phone)

    dependencies = [
        ('property', '0017_owner'),
    ]

    operations = [
        migrations.RunPython(load_users, migrations.RunPython.noop)
    ]
