# Generated by Django 2.2.24 on 2022-12-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    def load_users(self, schema_editor):
        Flat = self.get_model('property', 'Flat')
        Owner = self.get_model('property', 'Owner')
        for flat in Flat.objects.all():
            Owner.objects.get_or_create(owner_name=flat.owner,
                                        owner_phonenumber=flat.owners_phonenumber,
                                        owner_pure_phone=flat.owner_pure_phone)

    dependencies = [
        ('property', '0017_owner'),
    ]

    operations = [
        migrations.RunPython(load_users, migrations.RunPython.noop)
    ]
