# Generated by Django 2.2.24 on 2022-12-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    def load_flats(self, schema_editor):
        Flat = self.get_model('property', 'Flat')
        Owner = self.get_model('property', 'Owner')
        flats = Flat.objects.all()
        flats_iterator = flats.iterator()
        try:
            first_flat = next(flats_iterator)
        except StopIteration:
            pass
        else:
            from itertools import chain
            for flat in chain([first_flat], flats_iterator):
                owner, is_exists = Owner.objects.get_or_create(
                        name=flat.owner,
                        phonenumber=flat.owners_phonenumber,
                        defaults={
                            'name': flat.owner,
                            'phonenumber': flat.owners_phonenumber,
                            'pure_phonenumber': flat.owner_pure_phone
                        }
                )
                flat.owners.set([owner])

    dependencies = [
        ('property', '0020_auto_20221211_0148'),
    ]

    operations = [
        migrations.RunPython(load_flats, migrations.RunPython.noop)
    ]
