# Generated by Django 2.2.24 on 2022-12-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20221212_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
