# Generated by Django 2.2.24 on 2022-12-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20221212_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners',
            new_name='flats',
        ),
    ]
