# Generated by Django 2.2.24 on 2022-12-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_auto_20221212_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_flats', to='property.Flat', verbose_name='Кто лайкнул'),
        ),
    ]
