# Generated by Django 2.2.24 on 2022-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_auto_20221214_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='owners_likes', to='property.Owner', verbose_name='Кто лайкнул'),
        ),
    ]
